import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const seedPath = path.join(__dirname, '..', 'prisma', 'seed.db');
const outPath = path.join(__dirname, '..', 'src', 'config', 'seed-db.ts');

if (!fs.existsSync(seedPath)) {
  console.error('[embed-seed] Missing prisma/seed.db — run: DATABASE_URL=file:./seed.db npx prisma db push && npx tsx prisma/seed.ts');
  process.exit(1);
}

const base64 = fs.readFileSync(seedPath).toString('base64');
const content = `// Auto-generated by scripts/embed-seed.mjs — do not edit
export const SEED_DB_BASE64 = ${JSON.stringify(base64)};
`;

fs.writeFileSync(outPath, content);
console.log('[embed-seed] Wrote', outPath, `(${(base64.length / 1024).toFixed(1)} KB)`);
